#!/bin/bash

set -e

cd $(dirname $0)/..
PACKAGE=./gopath/src/$(<.package)
if [ -L "${PACKAGE}" ]; then
    rm ${PACKAGE}
fi

if [ ! -e "${PACKAGE}" ]; then
    mkdir -p $(dirname ${PACKAGE})
    ln -s $(pwd) ${PACKAGE}
fi

export GO15VENDOREXPERIMENT=1

get_version()
{
    VERSION=$(git tag -l --contains HEAD | head -n 1)
    if [ -z "$VERSION" ]; then
        VERSION=$(git rev-parse --short HEAD)
    fi
}

get_version

mkdir -p bin
echo Building Giddyup
CGO_ENABLED=0 go build  -o bin/giddyup -ldflags="-w -X github.com/rancher/giddyup/version.VERSION=${VERSION}"
