#!/bin/bash
set -e

cd $(dirname $0)/..

VERSION=$(git tag -l --contains HEAD | head -n 1)
if [ -z "$VERSION" ]; then
    VERSION=$(git rev-parse --short HEAD)
fi

go build  -o bin/giddyup -ldflags "-linkmode external -extldflags -static -s -w -X github.com/cloudnautique/giddyup/version.VERSION=${VERSION}"
