#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

cp ../bin/giddyup .
docker build -t ${REPO}/giddyup:${TAG} .

echo Built ${REPO}/giddyup:${TAG}
